apiVersion: v1
kind: Service
metadata:
  name: thread-service
  labels:
    app: dottit
    service: thread-service
spec:
  selector:
    app: thread-service
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
  type: LoadBalancer
