apiVersion: skaffold/v2beta29
kind: Config
requires:
  - path: "../message-bus"
  - path: "../mediator"
build:
  artifacts:
    - image: authorization-service
      context: ../../
      docker:
        dockerfile: services/authorization-service/Dockerfile
        noCache: false
        pullParent: false
        squash: false
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
    concurrency: 0
deploy:
  kubectl:
    manifests:
      # The order is important
      - "./k8s/dev/db/*.config.yml"
      - "./k8s/dev/db/*.pv.yml"
      - "./k8s/dev/db/*.yml"
      - "./k8s/dev/service/*.yml"
