apiVersion: v1
kind: Service
metadata:
  name: thread-service-postgres
  labels:
    app: dottit
    service: thread-service
spec:
  type: ClusterIP
  selector:
    app: thread-service-postgres-pod
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
