kind: PersistentVolume
apiVersion: v1
metadata:
  name: thread-service-mysql-pv
  labels:
    type: local
    app: dottit
    service: thread-service
  annotations:
    pv.beta.kubernetes.io/gid: "1234"
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/thread-service"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thread-service-mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
