[package]
name = "database"
version = "0.1.0"
edition = "2021"

[lib]
name = "database"
path = "src/lib.rs"

[dependencies]

diesel = { version = "2.0.0", features = ["mysql", "r2d2"] }
service = { path = "../service" }
model = { path = "../model" }
