apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: dottit
    service: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
  type: NodePort
