//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "board_moderator")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub board_id: Uuid,
  #[sea_orm(primary_key, auto_increment = false)]
  pub user_id:  Uuid
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
    belongs_to = "super::board::Entity",
    from = "Column::BoardId",
    to = "super::board::Column::Id",
    on_update = "NoAction",
    on_delete = "Cascade"
  )]
  Board
}

impl Related<super::board::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::Board.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
