//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "board")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id:   Uuid,
  #[sea_orm(unique)]
  pub name: String
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(has_many = "super::board_moderator::Entity")]
  BoardModerator
}

impl Related<super::board_moderator::Entity> for Entity {
  fn to() -> RelationDef {
    Relation::BoardModerator.def()
  }
}

impl ActiveModelBehavior for ActiveModel {}
