apiVersion: v1
kind: Service
metadata:
  name: board-service-postgres
  labels:
    app: dottit
    service: board-service
spec:
  type: ClusterIP
  selector:
    app: board-service-postgres-pod
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
