apiVersion: v1
kind: PersistentVolume
metadata:
  name: comment-service-postgres-pv
  labels:
    type: local
    app: dottit
    service: comment-service
  annotations:
    pv.beta.kubernetes.io/gid: "1234"
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/comment-service/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comment-service-postgres-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
