apiVersion: v1
kind: Service
metadata:
  name: comment-service-mysql
  labels:
    app: dottit
    service: comment-service
spec:
  type: ClusterIP
  selector:
    app: comment-service-mysql-pod
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
