apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service-mysql-pod
  labels:
    app: dottit
    service: comment-service
spec:
  selector:
    matchLabels:
      app: comment-service-mysql-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: comment-service-mysql-pod
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              # Check we can execute queries over TCP (skip-networking is off).
              command:
                ["mysql", "-h", "127.0.0.1", "-u", "root", "-e", "SELECT 1"]
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
          env:
            - name: MYSQL_DATABASE
              value: "comment_service"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
            - name: MYSQL_ROOT_HOST
              value: "%"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: comment-service-mysql-pv-claim
