apiVersion: skaffold/v2beta29
kind: Config
requires:
  - path: "../thread-service"
  - path: "../comment-service"
  - path: "../user-service"
  - path: "../authorization-service"
build:
  artifacts:
    - image: gateway-service
      context: .
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
    concurrency: 0
deploy:
  kubectl:
    manifests:
      # The order is important
      - "./k8s/dev/service/*.yml"
