name: "Prepare"
description: "Prepares for Rust builds"

inputs:
  target:
    description: The target platform
    required: true

runs:
  using: composite
  steps:
    - name: Fetch toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        components: rustfmt, clippy
        target: ${{ inputs.target }}
        toolchain: nightly
