name: "Prepare"
description: "Prepares for Rust builds"

inputs:
  toolchain:
    description: The rust toolchain to use
    required: true
  target:
    description: The target platform
    required: true

runs:
  using: composite
  steps:
    - name: Fetch toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ inputs.toolchain }}
        components: rustfmt, clippy
        target: ${{ inputs.target }}
