apiVersion: v1
kind: Service
metadata:
  name: mediator
  labels:
    app: dottit
    service: mediator
spec:
  selector:
    app: mediator
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
  type: LoadBalancer
