apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: dottit
    service: web-service
spec:
  selector:
    app: web-service
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: NodePort
