apiVersion: v1
kind: Service
metadata:
  name: authorization-service-redis
  labels:
    app: dottit
    service: authorization-service
spec:
  type: ClusterIP
  selector:
    app: authorization-service-redis-pod
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
