apiVersion: skaffold/v2beta29
kind: Config
requires:
  - path: "../message-bus"
  - path: "../authorization-service"
  - path: "../mediator"
build:
  artifacts:
    - image: user-service
      context: ../../
      docker:
        dockerfile: docker/dev/rust-service.Dockerfile
        buildArgs:
          BINARY: user-service-web
          SERVICE: user-service
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
    # concurrency: 0
deploy:
  kubectl:
    manifests:
      # The order is important
      - "./k8s/dev/db/*.pv.yml"
      - "./k8s/dev/db/*.yml"
      - "./k8s/dev/service/*.yml"
