//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "thread")]
pub struct Model {
  #[sea_orm(primary_key, auto_increment = false)]
  pub id:    Uuid,
  pub board: String,
  pub user:  String,
  pub title: String,
  #[sea_orm(column_type = "Text", nullable)]
  pub text:  Option<String>,
  #[sea_orm(column_type = "Text", nullable)]
  pub media: Option<String>,
  pub score: i32
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
  fn def(&self) -> RelationDef {
    panic!("No RelationDef")
  }
}

impl ActiveModelBehavior for ActiveModel {}
