apiVersion: skaffold/v2beta29
kind: Config
requires:
  - path: "../message-bus"
build:
  artifacts:
    - image: mediator
      context: ../../
      docker:
        dockerfile: docker/dev/rust-service.Dockerfile
        buildArgs:
          BINARY: mediator-web
          SERVICE: mediator
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
    # concurrency: 0
deploy:
  kubectl:
    manifests:
      # The order is important
      - "./k8s/dev/service/*.yml"
