apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
  labels:
    app: dottit
    service: comment-service
spec:
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
        - name: comment-service
          image: comment-service
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: MYSQL_ADDR
              value: comment-service-mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: comment_service
            - name: MYSQL_PASSWORD
              value: ""
      initContainers:
        - name: wait-for-comment-service-mysql
          image: imega/mysql-client:latest
          command:
            [
              "sh",
              "-c",
              'until mysql --verbose -h comment-service-mysql -u root -e "SELECT 1"; do echo waiting for mysql; sleep 2; done;',
            ]
