apiVersion: v1
kind: Service
metadata:
  name: comment-service
  labels:
    app: dottit
    service: comment-service
spec:
  selector:
    app: comment-service
  ports:
    - port: 80
      targetPort: 8080
      name: http
      protocol: TCP
  type: LoadBalancer
