apiVersion: skaffold/v2beta29
kind: Config
requires:
  - path: "../message-bus"
build:
  artifacts:
    - image: comment-service
      context: ../../
      docker:
        dockerfile: services/comment-service/Dockerfile
        noCache: false
        pullParent: false
        squash: false
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: false
deploy:
  kubectl:
    manifests:
      # The order is important
      - "./k8s/dev/db/*.pv.yml"
      - "./k8s/dev/db/*.yml"
      - "./k8s/dev/service/*.yml"
