name: AuthorizationService

on:
  push:
    branches:
      - "*"
    paths:
      - services/authorization-service/**
      - shared/shared-rust/**
      - .github/workflows/**
      - actions/**
      - docker/**
      - Cargo.toml
      - rust-toolchain.toml
      - rustfmt.toml
      - .dockerignore

env:
  bin: authorization-service-web
  target: aarch64-unknown-linux-musl
  package: authorization-service-*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/rust/build_service
        with:
          bin: ${{ env.bin }}
          target: ${{ env.target }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/rust/lint_service
        with:
          package: ${{ env.package }}
          target: ${{ env.target }}
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/rust/unit_test_service
        with:
          package: ${{ env.package }}
          target: ${{ env.target }}
