name: AuthorizationService

on:
  push:
    branches:
      - "*"
    paths:
      - services/authorization-service/**
      - shared/shared-rust/**
      - .github/workflows/**
      - docker/**
      - Cargo.toml
      - rust-toolchain.toml
      - rustfmt.toml
      - .dockerignore

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: /.github/actions/rust/build_service
        with:
          toolchain: nightly
          bin: authorization-service-web
          target: aarch64-unknown-linux-musl
