name: GatewayService

on:
  push:
    branches:
      - "main"
    paths:
      - services/gateway-service/**
      - shared/shared-rust/**
      - .github/workflows/**
      - actions/**
      - Cargo.toml
      - rust-toolchain.toml
      - rustfmt.toml
      - .dockerignore
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - services/gateway-service/**
      - shared/shared-rust/**
      - .github/workflows/**
      - actions/**
      - Cargo.toml
      - rust-toolchain.toml
      - rustfmt.toml
      - .dockerignore

env:
  bin: gateway-service
  target: aarch64-unknown-linux-musl
  package: gateway-service

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler
      - uses: actions/checkout@v2
      - uses: ./actions/rust/prepare
        with:
          target: ${{ env.target }}
      - uses: ./actions/rust/build_service
        with:
          bin: ${{ env.bin }}
          target: ${{ env.target }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler
      - uses: actions/checkout@v2
      - uses: ./actions/rust/prepare
        with:
          target: ${{ env.target }}
      - uses: ./actions/rust/lint_service
        with:
          package: ${{ env.package }}
          target: ${{ env.target }}
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler
      - uses: actions/checkout@v2
      - uses: ./actions/rust/prepare
        with:
          target: ${{ env.target }}
      - uses: ./actions/rust/unit_test_service
        with:
          package: ${{ env.package }}
          target: ${{ env.target }}
