apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: thread-service
      context: ./
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: false
deploy:
  kubectl:
    manifests:
      # The order is important
      - "./k8s/dev/db/*.pv.yml"
      - "./k8s/dev/db/*.yml"
      - "./k8s/dev/service/*.yml"
